module.exports = {
  getting_started: [
    'getting_started/intro_overview',
    'getting_started/doc_guide',
    {
      type: 'category',
      label: 'The Basics',
      items: [
        'documentation/client/client_overview',
        'documentation/client/basic_concepts',
        {
          type: 'category',
          label: 'User-Interface Basics',
          items: [
            'documentation/client/first_steps',
            'documentation/client/layout',
            'documentation/client/main_menu',
            'documentation/client/tool_bar',
            'documentation/client/groups',
            'documentation/client/channels',
            // 'documentation/client/videocalls',
          ],
          collapsed: true,
        },
        {
          type: 'category',
          label: 'Basic Tools',
          items: [
            'documentation/client/client_search',
            'documentation/client/actions_button',
            'documentation/client/surveys',
            'documentation/client/taskview',
            'documentation/client/database',
            'documentation/client/dashboard',
            'documentation/client/reports',
            {
              type: 'category',
              label: 'Notes',
              items: [
                'documentation/client/notes',
                'documentation/client/notes_markdown',
              ],
              collapsed: true,
            },
          ],
          collapsed: true,
        },
        'documentation/client/offline',
      ],
      collapsed: true,
    },
    'getting_started/support',
  ],
  documentation: [
    'documentation/documentation_overview',
    'documentation/admin_basic_concepts',
    {
      type: 'category',
      label: 'Administrative Panel',
      items: [
        'documentation/admin/admin_overview',
        {
          type: 'category',
          label: 'Sections',
          items: [
            {
              type: 'category',
              label: 'Workflows',
              items: [
                'documentation/admin/workflows/admin_workflow_overview',
                {
                  type: 'category',
                  label: 'Settings Panels',
                  items: [
                    'documentation/admin/workflows/settings_panels/workflowgroups-initial',
                    'documentation/admin/workflows/settings_panels/workflowgroup-create-edit',
                    'documentation/admin/workflows/settings_panels/workflowgroup_channels',
                    'documentation/admin/workflows/settings_panels/workflows-setup',
                    'documentation/admin/workflows/settings_panels/workflow_create_edit',
                    'documentation/admin/workflows/settings_panels/create_edit_state',
                  ],
                  collapsed: true,
                },
                {
                  type: 'category',
                  label: 'Basic Operations',
                  items: [
                    // 'documentation/admin/workflows/admin_workflow_configure',
                    'documentation/admin/workflows/admin_workflow_required_survey',
                    'documentation/admin/workflows/admin_workflow_public_survey',
                  ],
                  collapsed: true,
                },
              ],
              collapsed: true,
            },
            'documentation/admin/admin_links',
            {
              type: 'category',
              label: 'Groups',
              items: [
                'documentation/admin/groups/overview_groups',
                'documentation/admin/groups/admin_groups',
                'documentation/admin/groups/admin_channels',
              ],
              collapsed: true,
            },
          ],
          collapsed: false,
        },
        {
          type: 'category',
          label: 'Data',
          items: [
            {
              type: 'category',
              label: 'Database',
              items: [
                'documentation/admin/database/admin_database_overview',
                'documentation/admin/database/admin_collections',
                'documentation/admin/database/admin_elements',
              ],
              collapsed: true,
            },
            {
              type: 'category',
              label: 'Surveys',
              items: [
                'documentation/admin/survey/survey_overview',
                {
                  type: 'category',
                  label: 'Components',
                  items: [
                    {
                      type: 'autogenerated',
                      dirName: 'documentation/admin/survey/components',
                    },
                  ]
                }
              ],
              collapsed: true,
            },
            
          ],
          collapsed: false,
        },
        {
          type: 'category',
          label: 'Company',
          items: [
            'documentation/admin/users',
            'documentation/admin/admin_jobtitles',
            'documentation/admin/admin_company',
          ],
          collapsed: false,
        },
        {
          type: 'category',
          label: 'Automations',
          items: [
            'documentation/admin/admin_bots',
            'documentation/admin/admin_scheduler',
            'documentation/automation/automation_log',
            'documentation/admin/routines',
          ],
          collapsed: false,
        },
        {
          type: 'category',
          label: 'Security',
          items: [
            'documentation/admin/admin_accessrole',
            'documentation/admin/admin_token',
            'documentation/admin/admin_auditlogs',
          ],
          collapsed: false,
        },
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Automation Tools',
      items: [
        // 'documentation/automation/overview',
        'documentation/automation/admin_routine',
        'documentation/automation/existing_routines',
        'documentation/automation/question_exec',
        // 'documentation/automation/scheduling',
        'documentation/automation/sla',
        'documentation/automation/automation_log',
        'documentation/automation/admin_cotlang',
        'documentation/automation/triggers_and_contexts',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'BI & SQL',
      items: [
        'documentation/sql_bi/overview',
        'documentation/sql_bi/model',
        // 'documentation/sql_bi/bi_examples',
        // 'documentation/sql_bi/sql_examples',
        // 'documentation/sql_bi/sql_connection',
      ],
      collapsed: true,
    },
    {
      type: 'category',
      label: 'Special Configurations',
      items: [
        'documentation/admin/special_configurations/azure_config',
      ],
      collapsed: true,
    },
    // {
    //   type: 'category',
    //   label: 'Extensions (FAAS)',
    //   items:  [
    //     'documentation/extensions/overview',
    //     'documentation/extensions/getting_started',
    //     'documentation/extensions/cli',
    //     {
    //       type: 'category',
    //       label: 'Examples',
    //       items:  [
    //         'documentation/extensions/examples/send_survey',
    //         'documentation/extensions/examples/static_site',
    //         'documentation/extensions/examples/survey_api',
    //         'documentation/extensions/examples/write_api'
    //       ],
    //       collapsed: true,
    //     },
    //   ],
    //   collapsed: true,
    // },
    // {
    //   type: 'category',
    //   label: 'Infrastructure',
    //   items:  [
    //     'documentation/infrastructure/overview',
    //   ],
    //   collapsed: true,
    // }
   ],
  tutorials: [
    'tutorials/tutorial_overview',
    {
      type: 'category',
      label: 'Basic',
      items: [
        'tutorials/basic/configure_company',
        'tutorials/basic/create_accessroles',
        'tutorials/basic/create_user',
        'tutorials/basic/create_database',
        'tutorials/basic/create_group',
        'tutorials/basic/create_survey',
        'tutorials/basic/create_bot',
        'tutorials/basic/create_state_machines',
        'tutorials/basic/tutorial_taskview',

      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Intermediate',
      items: [
        'tutorials/intermediate/create_cmd_bot',
        'tutorials/intermediate/create_survey_sm',
        'tutorials/intermediate/create_survey_bot',
        'tutorials/intermediate/isCommanded',
        'tutorials/intermediate/sla',
        'tutorials/intermediate/tutorial_scheduler',
      ],
      collapsed: false,
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'tutorials/advanced/project_manager',
        'tutorials/advanced/tutorial_approval_flow',
        'tutorials/advanced/cutomizebot',
      ],
      collapsed: false,
    }
  ],
  // certification: [
  //   'certification/certification_overview',
  //   {
  //     type: 'category',
  //     label: '[1.a] Basic Admin',
  //     items: [
  //       'certification/basic_admin/certification_admin_ws1',
  //       'certification/basic_admin/certification_admin_ws2',
  //       'certification/basic_admin/certification_admin_ws3',
  //       'certification/basic_admin/certification_admin_ws4',
  //       'certification/basic_admin/certification_admin_ws5',
  //       'certification/basic_admin/certification_admin_ws6'
  //     ],
  //     collapsed: true,
  //   },

  // ],
  api: [
    'documentation/api/overview_api',
    'documentation/api/auth',
    'documentation/api/company',
    'documentation/api/users/users',
    'documentation/api/users/accessroles',
    'documentation/api/users/jobtitles',
    'documentation/api/communication/channels',
    'documentation/api/communication/messages',
    'documentation/api/communication/groups',
    'documentation/api/communication/files',
    'documentation/api/databases/property_types',
    'documentation/api/databases/properties',
    'documentation/api/surveys/surveys',
    'documentation/api/surveys/survey_chats',
    'documentation/api/surveys/questions',
    'documentation/api/surveys/answers',
    'documentation/api/tasks/tasks',
    'documentation/api/tasks/statemachines',
    'documentation/api/automations/bots',
    'documentation/api/automations/scheduler',
    'documentation/api/automations/pbscripts'
  ],
  models: [
    'documentation/models/overview_model',
    'documentation/models/users/model_accessroles',
    'documentation/models/surveys/model_answers',
    'documentation/models/surveys/model_answer_data',
    'documentation/models/automations/model_bots',
    'documentation/models/communication/model_channels',
    'documentation/models/model_company',
    'documentation/models/communication/file',
    'documentation/models/communication/model_groups',
    'documentation/models/users/model_jobtitles',
    'documentation/models/communication/model_messages',
    'documentation/models/communication/model_messageContent',
    'documentation/models/automations/model_parametrizedbot',
    'documentation/models/automations/model_pbscripts',
    'documentation/models/databases/model_properties',
    'documentation/models/databases/model_propertytypes',
    'documentation/models/surveys/model_questions',
    'documentation/models/surveys/model_questionContentType',
    'documentation/models/surveys/model_questionExec',
    'documentation/models/automations/model_scheduler',
    'documentation/models/tasks/model_sla',
    'documentation/models/tasks/model_state',
    'documentation/models/tasks/model_statemachine',
    'documentation/models/surveys/model_surveys',
    'documentation/models/surveys/model_surveychats',
    'documentation/models/tasks/model_tasks',
    'documentation/models/tasks/model_taskgroup',
    'documentation/models/users/model_users',
  ],
  support: [
    'support/support_overview',
    // 'support/commercial',
    // 'support/technical',
    // 'support/bug_report',
    // 'support/feature_request',
    // 'support/report_abuse',
  ],
  products: [
    {
      type: 'category',
      label: 'Products Overview',
      link: {
        type: 'doc',
        id: 'products/products_overview'
      },
      items: [
        'products/corrective_maintenance/cm_overview',
        'products/preventive_maintenance/pm_overview',
        'products/work_order_product/wo_overview',
      ],
      collapsed: false,
      collapsible: false
    },
    'products/setup/setup_overview'
  ],
  workflow_notifications: [
    {
      type: 'doc',
      id: 'products/corrective_maintenance/cm_overview',
      label: 'Back to Corrective Maintenance...'
    },
    {
      type: 'category',
      label: 'Notifications Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/notifications/overview',
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/notifications/examples',
        'products/workflows/notifications/workflow',
        {
          type: 'category',
          label: 'Survey Forms',
          link: {
            type: 'doc',
            id: 'products/workflows/notifications/surveys',
          },
          collapsed: false,
          collapsible: false,
          items: [
            'products/workflows/notifications/surveys-report',
            'products/workflows/notifications/surveys-validate',
          ]
        }
      ],
    }
  ],
  workflow_preventive_plan: [
    {
      type: 'doc',
      id: 'products/preventive_maintenance/pm_overview',
      label: 'Back to Preventive Maintenance...'
    },
    {
      type: 'category',
      label: 'Preventive Plans Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/preventive_plans/overview',
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/preventive_plans/sample',
        'products/workflows/preventive_plans/workflow',
        {
          type: 'category',
          label: 'Surveys & Input',
          link: {
            type: 'doc',
            id: 'products/workflows/preventive_plans/surveys'
          },
          collapsed: false,
          collapsible: false,
          items: [
            'products/workflows/preventive_plans/surveys-create-plan',
            'products/workflows/preventive_plans/surveys-plan-runner',
            'products/workflows/preventive_plans/surveys-update-metrics',
          ]
        },
      ]
    }
  ],
  workflow_workorders_wo: [
    {
      type: 'doc',
      id: 'products/work_order_product/wo_overview',
      label: 'Back to Work Orders...'
    },
    {
      type: 'category',
      label: 'Work Orders Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/work_orders/related-product/wo/overview_intro',
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/work_orders/related-product/wo/examples',
        'products/workflows/work_orders/related-product/wo/workflow',
        {
          type: 'category',
          label: 'Survey Forms',
          link: {
            type: 'doc',
            id: 'products/workflows/work_orders/related-product/wo/surveys'
          },
          collapsed: false,
          collapsible: false,
          items: [
            'products/workflows/work_orders/related-product/wo/surveys-create-wo',
            'products/workflows/work_orders/related-product/wo/surveys-accept-wo',
            'products/workflows/work_orders/related-product/wo/surveys-close-wo',
            'products/workflows/work_orders/related-product/wo/surveys-acceptance',
            'products/workflows/work_orders/related-product/wo/surveys-feedback',
            'products/workflows/work_orders/related-product/wo/mass_validation'
          ]
        },
      ]
    },
  ],
  workflow_workorders_cm: [
    {
      type: 'doc',
      id: 'products/corrective_maintenance/cm_overview',
      label: 'Back to Corrective Maintenance...'
    },
    {
      type: 'category',
      label: 'Work Orders Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/work_orders/related-product/cm/overview_intro',
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/work_orders/related-product/cm/examples',
        'products/workflows/work_orders/related-product/cm/workflow',
        {
          type: 'category',
          label: 'Survey Forms',
          link: {
            type: 'doc',
            id: 'products/workflows/work_orders/related-product/cm/surveys'
          },
          collapsed: false,
          collapsible: false,
          items: [
            'products/workflows/work_orders/related-product/cm/surveys-create-wo',
            'products/workflows/work_orders/related-product/cm/surveys-accept-wo',
            'products/workflows/work_orders/related-product/cm/surveys-close-wo',
            'products/workflows/work_orders/related-product/cm/surveys-acceptance',
            'products/workflows/work_orders/related-product/cm/surveys-feedback',
            'products/workflows/work_orders/related-product/cm/mass_validation'
          ]
        },
      ]
    },
  ],
  workflow_workorders_pm: [
    {
      type: 'doc',
      id: 'products/preventive_maintenance/pm_overview',
      label: 'Back to Preventive Maintenance...'
    },
    {
      type: 'category',
      label: 'Work Orders Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/work_orders/related-product/pm/overview_intro',
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/work_orders/related-product/pm/examples',
        'products/workflows/work_orders/related-product/pm/workflow',
        {
          type: 'category',
          label: 'Survey Forms',
          link: {
            type: 'doc',
            id: 'products/workflows/work_orders/related-product/pm/surveys'
          },
          collapsed: false,
          collapsible: false,
          items: [
            'products/workflows/work_orders/related-product/pm/surveys-accept-wo',
            'products/workflows/work_orders/related-product/pm/surveys-checklist-pm',
            'products/workflows/work_orders/related-product/pm/surveys-close-wo',
            'products/workflows/work_orders/related-product/pm/surveys-acceptance',
            'products/workflows/work_orders/related-product/pm/surveys-feedback',
            'products/workflows/work_orders/related-product/pm/mass_validation'
          ]
        },
      ]
    },
  ],
  workflow_quotes_cm: [
    {
      type: 'doc',
      id: 'products/corrective_maintenance/cm_overview',
      label: 'Back to Corrective Maintenance...'
    },
    {
      type: 'category',
      label: 'Quotes Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/budget_management/related-product/cm/overview'
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/budget_management/related-product/cm/surveys',
        'products/workflows/budget_management/related-product/cm/approval',
      ],
    }
  ],
  workflow_quotes_pm: [
    {
      type: 'doc',
      id: 'products/preventive_maintenance/pm_overview',
      label: 'Back to Preventive Maintenance...'
    },
    {
      type: 'category',
      label: 'Quotes Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/budget_management/related-product/pm/overview'
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/budget_management/related-product/pm/surveys',
        'products/workflows/budget_management/related-product/pm/approval',
      ],
    }
  ],
  workflow_quotes_wo: [
    {
      type: 'doc',
      id: 'products/work_order_product/wo_overview',
      label: 'Back to Work Orders...'
    },
    {
      type: 'category',
      label: 'Quotes Workflow',
      link: {
        type: 'doc',
        id: 'products/workflows/budget_management/related-product/wo/overview'
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/workflows/budget_management/related-product/wo/surveys',
        'products/workflows/budget_management/related-product/wo/approval',
      ],
    }
  ],
  Setup: [
    {
      type: 'category',
      label: 'Back to Setup Overview...',
      link: {
        type: 'doc',
        id: 'products/setup/setup_overview',
      },
      collapsed: false,
      collapsible: false,
      items: [
        'products/setup/users',
        'products/setup/master_data',
        'products/setup/customization',
        'products/setup/integrations',
      ]
    },
  ],
}
