name: Bug report
description: Use this template to report a new bug
title: 'Bug report: '
labels:
     - Bug report
assignees:
     - acedward
body:
- type: markdown
  attributes:
    value: |
     
     If you are looking for support, please check out our [Documentation](https://doc.cotalker.com/)
     or consider asking a question on [Discussions](https://github.com/Cotalker/documentation/discussions)
     If you have found a bug then fill out the template below.
     
     > :warning: **Please do not include any non-public information about your company, users and settings when posting an issue. Avoid entering data associated with access keys, passwords, data for internal use, user information or any other that you consider sensitive.**

- type: dropdown
  id: affected_system
  attributes:
    label: Affected system
    description: Please let us know which of our systems is affecting your Cotalker experience
    multiple: true
    options:
    - Cotalker Web Application
    - Cotalker Android Application
    - Cotalker iOS Application
    - Cotalker Api
  validations:
    required: true

- type: input
  id: affected_system_other
  attributes:
    label: Affected system (other)
    description: Please indicate any additional system affected by this issue

- type: dropdown
  id: affected_environment
  attributes:
    label: Affected environment
    description: Only change this answer if you have access to a special Cotalker environment such as Staging or Development, please indicate which environment it corresponds to.
    multiple: true
    options:
    - Production
    - Staging
    - Development
  validations:
    required: true

- type: input
  id: affected_environment_other
  attributes:
    label: Affected environment (other)
    description: Please indicate any additional environment affected by this issue

- type: input
  id: app_version
  attributes:
    label: App version
    description: |
     If this bug occurs in our web application, android or ios, please indicate the version
     > :information_source: To check app version follow this image ![Cotalker app version](/cotalker/documentation/blob/main/.github/ISSUE_TEMPLATE/assets/cotalker-app-version.gif?raw=true "Cotalker app version")
    placeholder: "16.4.5"
  validations:
    required: false

- type: textarea
  id: details
  attributes:
    label: Details
    description: Further details about the bug
    placeholder: |
      When I try to send a message...
  validations:
    required: true

- type: textarea
  id: steps_reproduce
  attributes:
    label: Steps to reproduce
    description: Please tell us exactly how to reproduce the problem you are running into
    placeholder: |
      1. ...
      2. ...
      3. ...ptional Title
  validations:
    required: true

- type: textarea
  id: expected_result
  attributes:
    label: Expected result
    description: Please explain to us what the expected result is after performing the steps described in the previous point
    placeholder: |
      After pressing the "Send" button the message should
  validations:
    required: true
  
- type: textarea
  id: additional_data
  attributes:
    label: Additional data
    description: Please, provide us with any additional information that you think may help our team to identify and correct the issue you are reporting
    placeholder: |
      - Company: ...<!-- id:... domain:... -->
      - Group: ...<!-- id:... code:... -->
      - Task: ...<!-- id:... code:... -->
      - Channel: ...<!-- id:... code:... -->
      - User: ...<!-- id:... email:... -->

- type: markdown
  attributes:
    value: "Thanks for reporting a bug!"
